### ISSUE TITLE
Request: Flexibility in descriptions

### ISSUE THREAD

**Issue by skyzyx** [Polyconseil/sphinx-dust#5]
I would like to be able to pass a custom setting to Dust which allows me to author my own message phrasing.

1. The "authored on" message and preferred datestamp format.
1. The "proofread on" message and preferred datestamp format.
1. The concatenation character.

I've made the following change for myself, but it would be nice if I could change this with a setting without having to edit the source code directly.

```python
written_strf = datetime.datetime.strftime(written_on, _("Authored on %A, %Y-%m-%d"))
proofread_strf = datetime.datetime.strftime(proofread_on, _("reviewed for accuracy on %A, %Y-%m-%d"))

content = statemachine.StringList(['; '.join([written_strf, proofread_strf])])
```

**Comment by lburg** [comment]
I've opened a PR including some changes that should solve your problem, please check it out and tell me if this looks good to you!

**Comment by skyzyx** [comment]
I've commented. Thank you. :)
