### ISSUE TITLE
Request: Custom admonition class name

### ISSUE THREAD

**Issue by skyzyx** [Polyconseil/sphinx-dust#6]
Previously, the classname on the admonition element was `admonition note`. In the latest release, it is `admonition`.

I would like to be able to configure a setting which allows me to set my own class name. I have made the following change in my local copy, but it would be better if this were a configuration.

```python
review_node['classes'].append('reviewed')
```

**Comment by lburg** [comment]
Ooh so that's why the HTML output lost its nice blue background, thanks for bringing this up! I opened a PR with a fix for this, it should provide enough customization.

**Comment by skyzyx** [comment]
I've commented. Thank you. :)
